const letterTypes = [
  'Acceptance Letter',
  'Acknowledgement Letter',
  'Apology Letter',
  'Appeal Letter',
  'Appreciation Letter',
  'Appreciation Letter',
  'Bank Transfer Letter',
  'Billing Letter',
  'Business Client Apology Letter',
  'Cancellation Letter',
  'Cease and Desist Letter',
  'Certification Letter',
  'Charity Letter',
  'Claim Authorization Letter',
  'Claim Letter',
  'Collection Letter',
  'College Acceptance Letter',
  'Complaint Letter',
  'Condolence Letter',
  'Congratulations Letter',
  'Contractual Appointment Letter',
  'Cover Letter',
  'Credit Letter',
  'Criticism Letter',
  'Deceased Estate Letter',
  'Delay Apology Letter',
  'Disciplinary Appeal Letter',
  'Dismissal Letter',
  'Dispute Letter',
  'Distributor Announcement Letter',
  'Document Collection Authorization Letter',
  'Donation Letter',
  'Endorsement Letter',
  'Farewell Letter',
  'Financial Appeal Letter',
  'Follow Up Letter',
  'Friendship Letter',
  'Fundraising Letter',
  'Grievance Letter',
  'Health Insurance Appeal Letter',
  'Inquiry Letter',
  'Internal Audit Letter',
  'Internship Acceptance Letter',
  'Internship Letter',
  'Interview Acceptance Letter',
  'Interview Letter',
  'Introduction Letter',
  'Invitation Letter',
  'Letter of Agreement',
  'Letter of Intent',
  'Marital Dissolution Agreement Letter',
  'Marketing Letter',
  'Medical Authorization Letter',
  'Offer Announcement Letter',
  'Operating Agreement Letter',
  'Part-time Appointment Letter',
  'Partnership Agreement Letter',
  'Permanent Job Appointment Letter',
  'Permission Letter',
  'Personal Loan Letter',
  'Product Complaint Letter',
  'Promotion Letter',
  'Property Tax Appeal Letter',
  'Recommendation Letter',
  'Renewal Letter',
  'Request Letter',
  'Request Letter',
  'Restoration Letter',
  'Retirement Announcement Letter',
  'Retirement Letter',
  'Sales Announcement Letter',
  'Sales Appointment Letter',
  'Sales Letter',
  'Scholarship Acceptance Letter',
  'Service Agreement Letter',
  'Short Sales Authorization Letter',
  'Sponsorship Letter',
  'Temporary Appointment Letter',
  'Termination Letter',
  'Thank You Letter',
  'Transfer Letter',
  'Travel Authorization Letter',
  'Travel Complaint Letter',
  'Unemployment Appeal Letter',
  'Warning Letter',
  'Welcome Letter',
];
export default letterTypes;
