<template>
  <div>
    <div class="section top-section">
      <div class="wrapper">
        <div class="page-intro">
          <h1 class="page-heading">Privacy Notice</h1>
          <div style="width: 0px" class="divider page-intro-divider"></div>
          <div class="breadcrumbs">
            <a href="#" class="breadcrumbs-link">Home</a>
            <div class="breadcrumbs-arrow"></div>
            <a href="#" class="breadcrumbs-link">Privacy Notice</a>
          </div>
        </div>
      </div>
      <div class="bg-elements">
        <div class="bg-element-1"></div>
        <div class="bg-element-2"></div>
        <div class="bg-element-3"></div>
        <div class="bg-element-4"></div>
      </div>
      <img
        src="@/assets/images/icons/decor-v1-haze.svg"
        alt=""
        class="decor-bottom"
      />
    </div>
    <div class="page-wrapper overflow-visible container">
      <div class="section haze"></div>
      <div class="rich-text-block w-richtext">
        <p>‍</p>
        <p>‍</p>
        <h4><strong>Effective date: 1/1/2021</strong></h4>
        <p>
          ‍<br />‍Welcome to <strong>HelloScribe LLC</strong>. HelloScribe LLC
          (“us”, “we”, or “our”) operates https://helloscribe.ai (hereinafter
          referred to as “<strong>Service</strong>”). <br />Our Privacy Policy
          governs your visit to https://helloscribe.ai, and explains how we
          collect, safeguard and disclose information that results from your use
          of our Service. <br /><br />We use your data to provide and improve
          Service. By using Service, you agree to the collection and use of
          information in accordance with this policy. Unless otherwise defined
          in this Privacy Policy, the terms used in this Privacy Policy have the
          same meanings as in our Terms and Conditions. <br /><br />Our Terms
          and Conditions (“<strong>Terms</strong>”) govern all use of our
          Service and together with the Privacy Policy constitutes your
          agreement with us (“<strong>agreement</strong>”).<br /><br /><strong
            >Definitions <br />SERVICE </strong
          >means the https://helloscribe.ai website operated by HelloScribe LLC.
          <br />‍<br />‍<strong>PERSONAL DATA</strong> means data about a living
          individual who can be identified from those data (or from those and
          other information either in our possession or likely to come into our
          possession). <br />‍<br />‍<strong>USAGE DATA</strong> is data
          collected automatically either generated by the use of Service or from
          Service infrastructure itself (for example, the duration of a page
          visit).
        </p>
        <p>
          ‍<br />‍<strong>COOKIES</strong> are small files stored on your device
          (computer or mobile device). <br />‍<br />‍<strong
            >DATA CONTROLLER</strong
          >
          means a natural or legal person who (either alone or jointly or in
          common with other persons) determines the purposes for which and the
          manner in which any personal data are, or are to be, processed. For
          the purpose of this Privacy Policy, we are a Data Controller of your
          data. <br />‍<br />‍<strong
            >DATA PROCESSORS (OR SERVICE PROVIDERS)</strong
          >
          means any natural or legal person who processes the data on behalf of
          the Data Controller. We may use the services of various Service
          Providers in order to process your data more effectively.
        </p>
        <p>
          ‍<br /><strong>DATA SUBJECT </strong>is any living individual who is
          the subject of Personal Data. <br />‍<br />‍<strong>THE USER </strong
          >is the individual using our Service. The User corresponds to the Data
          Subject, who is the subject of Personal Data.<br /><br /><strong
            >Information Collection and Use </strong
          >We collect several different types of information for various
          purposes to provide and improve our Service to you.
          <br />‍<br />‍<strong
            >Types of Data Collected <br />‍<br />Personal Data <br />‍</strong
          >While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“<strong>Personal Data</strong>”). Personally
          identifiable information may include, but is not limited to: Email
          address First name and last name Phone number Cookies and Usage Data
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link.
          <br /><br />‍<strong>Usage Data<br />‍</strong>We may also collect
          information that your browser sends whenever you visit our Service or
          when you access Service by or through a mobile device (“<strong
            >Usage Data</strong
          >”). This Usage Data may include information such as your
          computer&#x27;s Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, unique
          device identifiers and other diagnostic data. When you access Service
          with a mobile device, this Usage Data may include information such as
          the type of mobile device you use, your mobile device unique ID, the
          IP address of your mobile device, your mobile operating system, the
          type of mobile Internet browser you use, unique device identifiers and
          other diagnostic data. <br />‍<br />‍<strong
            >Tracking Cookies Data<br />‍</strong
          >We use cookies and similar tracking technologies to track the
          activity on our Service and we hold certain information. Cookies are
          files with a small amount of data which may include an anonymous
          unique identifier. Cookies are sent to your browser from a website and
          stored on your device. Other tracking technologies are also used such
          as beacons, tags and scripts to collect and track information and to
          improve and analyze our Service. You can instruct your browser to
          refuse all cookies or to indicate when a cookie is being sent.
          However, if you do not accept cookies, you may not be able to use some
          portions of our Service. Examples of Cookies we use:
          <strong>Session Cookies:</strong> We use Session Cookies to operate
          our Service. <strong>Preference Cookies:</strong> We use Preference
          Cookies to remember your preferences and various settings.
          <strong>Security Cookies:</strong> We use Security Cookies for
          security purposes. <strong>Advertising Cookies:</strong> Advertising
          Cookies are used to serve you with advertisements that may be relevant
          to you and your interests. <br />‍<br />‍<strong
            >Use of Data <br />‍</strong
          >HelloScribe LLC uses the collected data for various purposes: to
          provide and maintain our Service; to notify you about changes to our
          Service; to allow you to participate in interactive features of our
          Service when you choose to do so; to provide customer support; to
          gather analysis or valuable information so that we can improve our
          Service; to monitor the usage of our Service; to detect, prevent and
          address technical issues; to fulfill any other purpose for which you
          provide it; to carry out our obligations and enforce our rights
          arising from any contracts entered into between you and us, including
          for billing and collection; to provide you with notices about your
          account and/or subscription, including expiration and renewal notices,
          email-instructions, etc.; to provide you with news, special offers and
          general information about other goods, services and events which we
          offer that are similar to those that you have already purchased or
          enquired about unless you have opted not to receive such information;
          in any other way we may describe when you provide the information; for
          any other purpose with your consent. <br /><br />‍<strong
            >Retention of Data<br /> </strong
          >We will retain your Personal Data only for as long as is necessary
          for the purposes set out in this Privacy Policy. We will retain and
          use your Personal Data to the extent necessary to comply with our
          legal obligations (for example, if we are required to retain your data
          to comply with applicable laws), resolve disputes, and enforce our
          legal agreements and policies. We will also retain Usage Data for
          internal analysis purposes. Usage Data is generally retained for a
          shorter period, except when this data is used to strengthen the
          security or to improve the functionality of our Service, or we are
          legally obligated to retain this data for longer time periods.
          <br />‍<br />‍<strong>Transfer of Data <br />‍</strong>Your
          information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction. If you are located
          outside United States and choose to provide information to us, please
          note that we transfer the data, including Personal Data, to United
          States and process it there. Your consent to this Privacy Policy
          followed by your submission of such information represents your
          agreement to that transfer. HelloScribe LLC will take all the steps
          reasonably necessary to ensure that your data is treated securely and
          in accordance with this Privacy Policy and no transfer of your
          Personal Data will take place to an organisation or a country unless
          there are adequate controls in place including the security of your
          data and other personal information. <br /><br />‍<strong
            >Disclosure of Data<br /> </strong
          >We may disclose personal information that we collect, or you provide:
        </p>
        <p>
          ‍<br />‍<strong>Disclosure for Law Enforcement.<br />‍</strong>Under
          certain circumstances, we may be required to disclose your Personal
          Data if required to do so by law or in response to valid requests by
          public authorities.
        </p>
        <p>
          ‍<br />‍<strong>Business Transaction.<br />‍</strong>If we or our
          subsidiaries are involved in a merger, acquisition or asset sale, your
          Personal Data may be transferred. <br /><br />‍<strong
            >Other cases. We may disclose your information also: </strong
          >to our subsidiaries and affiliates; to fulfill the purpose for which
          you provide it; with your consent in any other cases; if we believe
          disclosure is necessary or appropriate to protect the rights,
          property, or safety of the Company, our customers, or others.
          <br /><br />‍<strong>Security of Data <br />‍</strong>The security of
          your data is important to us but remember that no method of
          transmission over the Internet or method of electronic storage is 100%
          secure. While we strive to use commercially acceptable means to
          protect your Personal Data, we cannot guarantee its absolute security.
          <br /><br />‍<strong
            >Your Data Protection Rights Under General Data Protection
            Regulation (GDPR) </strong
          >If you are a resident of the European Union (EU) and European
          Economic Area (EEA), you have certain data protection rights, covered
          by GDPR. – See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data. If you wish to be
          informed what Personal Data we hold about you and if you want it to be
          removed from our systems, please email us at legal@helloscribe.ai.
          <br /><br /><br /><br />‍<br /><br />‍
        </p>
        <p>‍</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Privacy",
};
</script>